export {default as HomePage} from './home'
export {default as LoginPage} from './login'
export {default as RegisterPage} from './register'
export {default as ForgotPassPage} from './forgotpass'
export {default as RedefinePassPage} from './redefinepass'